# Generated by Django 4.0 on 2021-12-28 09:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gama', '0004_jaccs_jacms_jacps_jamcs_jamms_jamps_jatcs_jatms_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='jbccs',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=1000)),
                ('batan', models.CharField(default='some_string', max_length=1000)),
                ('url', models.CharField(default='some_string', max_length=1000)),
            ],
        ),
        migrations.CreateModel(
            name='jbcms',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=1000)),
                ('batan', models.CharField(default='some_string', max_length=1000)),
                ('url', models.CharField(default='some_string', max_length=1000)),
            ],
        ),
        migrations.CreateModel(
            name='jbcps',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=1000)),
                ('batan', models.CharField(default='some_string', max_length=1000)),
                ('url', models.CharField(default='some_string', max_length=1000)),
            ],
        ),
        migrations.CreateModel(
            name='jbmcs',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=1000)),
                ('batan', models.CharField(default='some_string', max_length=1000)),
                ('url', models.CharField(default='some_string', max_length=1000)),
            ],
        ),
        migrations.CreateModel(
            name='jbmms',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=1000)),
                ('batan', models.CharField(default='some_string', max_length=1000)),
                ('url', models.CharField(default='some_string', max_length=1000)),
            ],
        ),
        migrations.CreateModel(
            name='jbmps',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=1000)),
                ('batan', models.CharField(default='some_string', max_length=1000)),
                ('url', models.CharField(default='some_string', max_length=1000)),
            ],
        ),
        migrations.CreateModel(
            name='jbtcs',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=1000)),
                ('batan', models.CharField(default='some_string', max_length=1000)),
                ('url', models.CharField(default='some_string', max_length=1000)),
            ],
        ),
        migrations.CreateModel(
            name='jbtms',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=1000)),
                ('batan', models.CharField(default='some_string', max_length=1000)),
                ('url', models.CharField(default='some_string', max_length=1000)),
            ],
        ),
        migrations.CreateModel(
            name='jbtps',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=1000)),
                ('batan', models.CharField(default='some_string', max_length=1000)),
                ('url', models.CharField(default='some_string', max_length=1000)),
            ],
        ),
    ]
