# Generated by Django 4.0 on 2021-12-28 15:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('gama', '0005_jbccs_jbcms_jbcps_jbmcs_jbmms_jbmps_jbtcs_jbtms_and_more'),
    ]

    operations = [
        migrations.DeleteModel(
            name='video',
        ),
    ]
