# Generated by Django 4.0 on 2021-12-27 17:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gama', '0003_bcbio_bcchem_bcmath_bcphy_bmbio_bmchem_bmmath_bmphy_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='jaccs',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=1000)),
                ('batan', models.CharField(default='some_string', max_length=1000)),
                ('url', models.CharField(default='some_string', max_length=1000)),
            ],
        ),
        migrations.CreateModel(
            name='jacms',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=1000)),
                ('batan', models.CharField(default='some_string', max_length=1000)),
                ('url', models.CharField(default='some_string', max_length=1000)),
            ],
        ),
        migrations.CreateModel(
            name='jacps',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=1000)),
                ('batan', models.CharField(default='some_string', max_length=1000)),
                ('url', models.CharField(default='some_string', max_length=1000)),
            ],
        ),
        migrations.CreateModel(
            name='jamcs',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=1000)),
                ('batan', models.CharField(default='some_string', max_length=1000)),
                ('url', models.CharField(default='some_string', max_length=1000)),
            ],
        ),
        migrations.CreateModel(
            name='jamms',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=1000)),
                ('batan', models.CharField(default='some_string', max_length=1000)),
                ('url', models.CharField(default='some_string', max_length=1000)),
            ],
        ),
        migrations.CreateModel(
            name='jamps',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=1000)),
                ('batan', models.CharField(default='some_string', max_length=1000)),
                ('url', models.CharField(default='some_string', max_length=1000)),
            ],
        ),
        migrations.CreateModel(
            name='jatcs',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=1000)),
                ('batan', models.CharField(default='some_string', max_length=1000)),
                ('url', models.CharField(default='some_string', max_length=1000)),
            ],
        ),
        migrations.CreateModel(
            name='jatms',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=1000)),
                ('batan', models.CharField(default='some_string', max_length=1000)),
                ('url', models.CharField(default='some_string', max_length=1000)),
            ],
        ),
        migrations.CreateModel(
            name='jatps',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=1000)),
                ('batan', models.CharField(default='some_string', max_length=1000)),
                ('url', models.CharField(default='some_string', max_length=1000)),
            ],
        ),
    ]
